### ISSUE TITLE
Navigate back to source category

### ISSUE THREAD

**Issue by alkumaish** [Suwayomi/Tachidesk-VUI#55]
Navigating back from a comic/manga main page using the "Back arrow" or even using the browsers "back" takes me back to the Library as expected but it does not go back to the originating "Category".  Instead it goes back to the 1st category in the list.

Current behaviour:  Going back from the comic main page takes me to the default/1st category in the library.

Expected behaviour: It should go back to the originating Category. preferably to the tile/thumbnail of the comic itself

**Comment by Robonau** [comment]
VUI3 fixes this
