### ISSUE TITLE
Reading mode menu

### ISSUE THREAD

**Issue by alkumaish** [Suwayomi/Tachidesk-VUI#56]
Clicking/tapping the center of the page makes the menu pop up from the left side.
Clicking away from the menu side bar should make the menu disappear (Unless a persistent/static toggle is enabled. but this is not an option right now)

Also, the Arrow and X on the menu behave in a different way compared to all other Suwayomi interfaces.  Here the "X" closes the menu while the arrow exits the reading mode.   Maybe using a hamburger icon instead of X will be better here?

**Comment by Robonau** [comment]
1. VUI3 fixes this
2. X to close menu and back button to go back makes more sense than the opposite
