### ISSUE TITLE
Keyboard navigation in reading mode

### ISSUE THREAD

**Issue by alkumaish** [Suwayomi/Tachidesk-VUI#57]
Space (or shift+space) and Left/right arrows should have the same behaviour as the PageUp/PageDown.   
Currently space scrolls half a page, while Left/Right arrow keys don't do anything.

Space = PageDown
Shift+Space = Backspace = PageUp
Left/Right arrow keys behaviour should be similar to PgUP/PgDn but it should depend on the reading mode (RTL vs LTR)

Maybe, for fun, add  ASDW navigation for gamers? (HJKL for VI users?)

**Comment by alkumaish** [comment]
https://github.com/Suwayomi/Tachidesk-WebUI/pull/200

**Comment by Robonau** [comment]
VUI3 fixes this
magic scroll = if top of next page visible scroll to page top else scroll 80% of screen height

space,right arrow,down arrow = magic scroll down
shift + space, left arrow, up arrow = scroll up 80%

PgUP/PgDn will have focus issues so i don't suggest using them
