### ISSUE TITLE
[Feature Request] Next-chapter preloading.

### ISSUE THREAD

**Issue by alkumaish** [Suwayomi/Tachidesk-VUI#81]
Maybe it's already planned, but it'd be great to have next-chapter(s) preloading again in VUI3 (+ configurable: Toggles/No of ch preloaded).

Preloading is great when reading short comics from slow sources.

**Comment by Robonau** [comment]
closed with #86

**Comment by Robonau** [comment]
just a note, im more likely to see the message if u send it in discord than as an issue (hence me not seeing the old ones for almost 6 months)
